[package]
name = "ghop"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "io-util", "time", "sync"] }
anyhow = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
